import { Badge } from "@/components/ui/Badge";
import { getPresentationContent } from "@/lib/content";
import { ItemGrid, PresentationCallout, PresentationSlide, PresentationSlideBody, PresentationSlideFooter, PresentationSlideHeader } from "@/components/presentation/PresentationPrimitives";
import { InlineInfoDialog } from "@/components/presentation/InlineInfoDialog";

export function SystemsIntegrationPage() {
  const { integration } = getPresentationContent();
  return <PresentationSlide><PresentationSlideHeader eyebrow="Parte 3 · Integración de sistemas" title="ERP como núcleo, eventos como contrato" thesis="APIs para intención, eventos para hechos, jobs para trabajo largo y connectors como boundary externo." actions={<InlineInfoDialog eyebrow="Integración" id="integration-detail-dialog" title="Endpoint, eventos y fallos"><div className="dialog-grid"><div className="dialog-panel"><Badge tone="info">{integration.endpoint.method}</Badge><h3><code>{integration.endpoint.path}</code></h3><ol>{integration.endpoint.steps.map((step) => <li key={step}>{step}</li>)}</ol></div><div className="dialog-panel"><h3>Eventos obligatorios</h3>{integration.events.map((event) => <p key={event.name}><b>{event.name}.v{event.version}</b>: {event.idempotency}</p>)}</div><div className="dialog-panel"><h3>Manejo de fallos</h3><ItemGrid items={integration.failureHandling} columns={3} /></div></div></InlineInfoDialog>} /><PresentationSlideBody><div className="integration-layers">{integration.systems.map((system, index) => <section className={`layer ${index === 0 ? "core" : index < 4 ? "engines" : "connectors"}`} key={system.id}><header><span>PLANE {index + 1}</span><b>{system.title}</b><small>{system.tone ?? "info"}</small></header><p>{system.description}</p></section>)}</div><div className="integration-rails"><div><span>COMMAND</span><b>API síncrona</b><p>Intención autorizada.</p></div><div><span>FACT</span><b>Evento asíncrono</b><p>Hecho committed.</p></div><div><span>WORK</span><b>Job / Queue</b><p>Proceso largo recuperable.</p></div><div><span>EXTERNAL</span><b>Connector Runtime</b><p>Boundary server-to-server.</p></div></div></PresentationSlideBody><PresentationSlideFooter><span>Sin backend nuevo</span><PresentationCallout><b>La ruta sigue siendo presentación estática: no se crean APIs ni fetch runtime.</b></PresentationCallout></PresentationSlideFooter></PresentationSlide>;
}
