import { Fragment } from "react";
import { Badge } from "@/components/ui/Badge";
import { getPresentationContent } from "@/lib/content";
import { ItemGrid, PresentationPageHero, Section } from "@/components/presentation/PresentationPrimitives";

export function DataModelingPage() {
  const { dataModeling } = getPresentationContent();
  return <><PresentationPageHero eyebrow="Parte 4 · Modelado de datos" title="Del cliente a factura con estados explícitos" lead="Modelo relacional orientado al value stream: cada entidad tiene owner, relaciones, lifecycle e integridad." /><Section title="Diagrama entidad-relación" description="Cardinalidades principales y flujo accesible desde cliente hasta factura."><div className="entity-flow">{["Client", "Project", "MPO", "Mission", "MediaBatch", "Deliverable", "Invoice"].map((name, index, arr) => <Fragment key={name}><article className="flow-node"><Badge tone="info">{index === 0 ? "1" : "N"}</Badge><h3>{name}</h3></article>{index < arr.length - 1 ? <span className="arrow">→</span> : null}</Fragment>)}</div><p className="muted">Leyenda: flechas representan dependencia operacional; UserRole aplica como alcance transversal por usuario, rol y recurso.</p></Section><Section title="Catálogo de entidades"><div className="grid grid-4">{dataModeling.entities.map((entity) => <article className="card" key={entity.name}><Badge tone="info">{entity.owner}</Badge><h3 style={{ marginTop: 10 }}>{entity.name}</h3><p>{entity.responsibility}</p><p><b>Campos:</b> {entity.fields.join(" · ")}</p><p><b>Relaciones:</b> {entity.relationships.join(" · ")}</p><p><b>Estados:</b> {entity.states.join(" → ")}</p><p><b>Lifecycle:</b> {entity.lifecycle.join(" → ")}</p><p><b>Integridad:</b> {entity.integrityRules.join("; ")}</p></article>)}</div></Section><Section title="Relaciones y lifecycles"><ItemGrid items={dataModeling.relationships} columns={3} /><div style={{ marginTop: 16 }}><ItemGrid items={dataModeling.lifecycles} columns={4} /></div></Section></>;
}
