import { Fragment } from "react";
import { Badge } from "@/components/ui/Badge";
import { getPresentationContent } from "@/lib/content";
import { ItemGrid, PresentationCallout, PresentationSlide, PresentationSlideBody, PresentationSlideFooter, PresentationSlideHeader } from "@/components/presentation/PresentationPrimitives";
import { InlineInfoDialog } from "@/components/presentation/InlineInfoDialog";

export function DataModelingPage() {
  const { dataModeling } = getPresentationContent();
  return <PresentationSlide><PresentationSlideHeader eyebrow="Parte 4 · Modelado de datos" title="Del cliente a factura con estados explícitos" thesis="El modelo sigue el value stream: cada entidad tiene owner, relaciones, lifecycle e integridad." actions={<InlineInfoDialog eyebrow="Datos" id="data-detail-dialog" title="Catálogo completo de entidades"><div className="dialog-grid"><div className="dialog-panel entity-catalog">{dataModeling.entities.map((entity) => <article className="entity-card" key={entity.name}><header><b>{entity.name}</b><span>{entity.owner}</span></header><p>{entity.responsibility}</p><code>{entity.fields.join(" · ")}</code><p><b>Relaciones:</b> {entity.relationships.join(" · ")}</p><p><b>Estados:</b> {entity.states.join(" → ")}</p><p><b>Lifecycle:</b> {entity.lifecycle.join(" → ")}</p><p><b>Integridad:</b> {entity.integrityRules.join("; ")}</p></article>)}</div><div className="dialog-panel"><h3>Relaciones</h3><ItemGrid items={dataModeling.relationships} columns={3} /></div><div className="dialog-panel"><h3>Lifecycles</h3><ItemGrid items={dataModeling.lifecycles} columns={4} /></div></div></InlineInfoDialog>} /><PresentationSlideBody><div className="domain-flow">{dataModeling.entities.filter((entity) => entity.name !== "UserRole").map((entity, index, arr) => <Fragment key={entity.name}><div className={index === 0 || entity.name === "Project" || entity.name === "Mission" ? "domain-node root" : "domain-node"}><span>{String(index + 1).padStart(2, "0")}</span><b>{entity.name}</b><small>{entity.owner}</small></div>{index < arr.length - 1 ? <i>→</i> : null}</Fragment>)}</div><div className="model-insights">{dataModeling.entities.slice(0, 4).map((entity) => <div key={entity.name}><b>{entity.name}</b><p>{entity.responsibility}</p></div>)}</div></PresentationSlideBody><PresentationSlideFooter><span>Modelo operacional</span><PresentationCallout><b>UserRole conserva el scope transversal sin convertirse en bypass de permisos.</b></PresentationCallout><Badge tone="info">8 entidades</Badge></PresentationSlideFooter></PresentationSlide>;
}
