import { ButtonLink } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { getPresentationContent } from "@/lib/content";
import { ItemGrid, PresentationCallout, PresentationSlide, PresentationSlideBody, PresentationSlideFooter, PresentationSlideHeader } from "@/components/presentation/PresentationPrimitives";
import { InlineInfoDialog } from "@/components/presentation/InlineInfoDialog";

export function HomePage() {
  const { home } = getPresentationContent();
  return <PresentationSlide className="cover-slide"><PresentationSlideHeader eyebrow="Preámbulo · 0 de 6" title={home.title} thesis={home.intro} actions={<InlineInfoDialog eyebrow="Índice" id="home-detail-dialog" title="Contenido completo de inicio"><div className="dialog-grid"><div className="dialog-panel"><h3>Sistemas incluidos</h3><div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>{home.systems.map((system) => <Badge key={system} tone="info">{system}</Badge>)}</div></div><div className="dialog-panel"><h3>Partes</h3><ItemGrid items={home.parts} columns={3} /></div></div></InlineInfoDialog>} /><PresentationSlideBody><div className="cover-grid"><section className="cover-copy"><div className="status-line"><span className="pulse-dot" /> Presentación ejecutiva interactiva</div><h2>Una plataforma ejecutable, no un documento de alcance.</h2><PresentationCallout><b>Tesis</b><p>{home.recommendation}</p></PresentationCallout><div className="cover-actions"><ButtonLink href="/architecture-review/" variant="primary">Comenzar presentación</ButtonLink></div></section><aside className="cover-panel"><div className="radar"><b>0/6</b></div><div className="cover-stats"><div><strong>6</strong><span>partes</span></div><div><strong>8</strong><span>roadmaps</span></div><div><strong>365</strong><span>días</span></div><div><strong>0</strong><span>backend</span></div></div></aside></div></PresentationSlideBody><PresentationSlideFooter><span>InflightOS</span><span>Use el menú lateral o avance linealmente.</span><ButtonLink href="/architecture-review/" variant="ghost">Siguiente</ButtonLink></PresentationSlideFooter></PresentationSlide>;
}
